name: Quality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    container:
      image: ramageek/image:php8.3-laravel-dev
      options: --workdir /var/www/html

    steps:
      - name: PWD
        run: pwd

      - name: LS
        run: cd /var/www && rm -rf html && git clone https://github.com/ramaID/playground-11.git html && cd html && ls

      - name: Verify Clone
        run: |
          if [ -d "/var/www/html" ]; then
            echo "Repository cloned successfully"
            cd /var/www/html && ls -la
          else
            echo "Clone failed"
            exit 1
          fi

      - name: Show Status
        run: |
          pwd
          git status
        working-directory: /var/www/html

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-interaction --optimize-autoloader --quiet

      - name: Generate application key
        run: php artisan key:gen

      - name: Copy .env to .env.testing
        run: cp .env .env.testing

      - name: Run Composer quality check
        run: composer qc

      - name: Copy sonar-project.properties.example to sonar-project.properties
        run: cp sonar-project.properties.example sonar-project.properties

      - name: Run Sonar Scanner
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
